version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:175937889706:task-definition/dockerwithmysql:2"
        LoadBalancerInfo:
          ContainerName: "dockerwithmysql"
          ContainerPort: "80"
        PlatformVersion: "LATEST"